files:
  include: '**/**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  attribute-quotes:
    - 1
    - include: true
  bem-depth:
    - 1
    - max-depth: 2
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - style: '1tbs'
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedbem
  extends-before-declarations: 0
  extends-before-mixins: 0
  empty-line-between-blocks: 
    - 1
    - include: true
  force-element-nesting: 1
  force-pseudo-nesting: 1
  function-name-format: 1
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: true
  mixin-name-format: 1
  mixins-before-declarations: 0
  no-color-literals: 1
  no-qualifying-elements: 0
  no-duplicate-properties: 1
  no-trailing-zero: 1
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order:
    - 1
    - order: recess
  pseudo-element : 1
  quotes:
    - 1
    - style: double
  shorthand-values:
    - 1
    - allowed-shorthands:
        - 1
        - 2
  single-line-per-selector: 1
  trailing-semicolon:
    - 1
    - include: true
  url-quotes: 1
  variable-name-format: 1
  zero-unit:
    - 1
    - include: false
